import React from "react";
import { Router, useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
import data from "../../coffee-stores.json";
import Image from "next/image";
import styles from "../../styles/coffee-store.module.css";
import cls from "classnames";

//Will display our prerendered coffees shop from pre rendered paths
export async function getStaticProps({ params }) {
  return {
    props: {
      coffeeStore: data.find((store) => store.id.toString() === params.id),
    }, // will be passed to the page component as props
  };
}

export async function getStaticPaths() {
  const paths = data.map((path) => ({
    params: { id: path.id.toString() },
  }));
  return {
    paths,
    fallback: false, // false or 'blocking'
  };
}
const CoffeeStore = (props) => {
  const router = useRouter();
  const { name, imgUrl, websiteUrl, address, neighbourhood } =
    props.coffeeStore;
  const handleUpvoteButton = () => {
    console.log("up vote");
  };
  return (
    <div className={styles.layout}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {router.isFallback && <h1>Loading</h1>}
      <div className={styles.container}>
        <div className={styles.col1}>
          <div className={styles.backToHomeLink}>
            <Link href="/">
              <a>Go Home</a>
            </Link>
          </div>
          <p style={{ color: "white" }}>{name}</p>
          <Image width={600} height={360} src={imgUrl} alt={name} />
        </div>

        <div className={cls("glass", styles.col2)}>
          <div className={styles.iconWrapper}>
            <Image
              src="/static/icons/places.svg"
              width={24}
              height={24}
              alt=""
            />
            <p className={styles.text} style={{ color: "white" }}>
              {address}
            </p>
          </div>
          <div className={styles.iconWrapper}>
            <Image
              src="/static/icons/nearMe.svg"
              width={24}
              height={24}
              alt=""
            />
            <p className={styles.text} style={{ color: "white" }}>
              {neighbourhood}
            </p>
          </div>
          <div className={styles.iconWrapper}>
            <Image src="/static/icons/star.svg" width={24} height={24} alt="" />
            <p className={styles.text} style={{ color: "white" }}>
              {1}
            </p>
          </div>
          <button onClick={handleUpvoteButton} className={styles.upvoteButton}>
            Up Vote!
          </button>
          <p style={{ color: "white" }}>{websiteUrl}</p>
        </div>
      </div>
    </div>
  );
};

export default CoffeeStore;
