import React from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";

const CoffeeStore = () => {
  const router = useRouter();
  console.log(router);
  return (
    <div>
      <Head>
        <title>{router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Coffee Store page{router.query.id}
      <Link href="/">
        <a>Go Home</a>
      </Link>
    </div>
  );
};

export default CoffeeStore;
