import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { Banner } from "../components/Banner";
import { Card } from "../components/Card";
import styles from "../styles/Home.module.css";
import data from "../coffee-stores.json";

interface Data {
  Coffedata: {
    id: number;
    name: string;
    imgUrl: string;
    websiteUrl: string;
    address: string;
    neighbourhood: string;
  }[];
}

export async function getStaticProps(context) {
  return {
    props: {
      Coffedata: data,
    }, // will be passed to the page component as props
  };
}
export default function Home(props: Data) {
  console.log(`data:${data[0] && data[0].name}`);
  console.log("props", props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          title1="Coffee"
          title2="Connoisseur"
          subTitle="Discover your local coffe shops"
          btnText="View stores near by"
        />
        <div className={styles.heroImage}>
          <Image
            width={700}
            height={400}
            src={"/static/hero-image.png"}
            alt=""
          />
        </div>
        <h2 className={styles.heading2}>
          {props.Coffedata.length !== 0 ? "Toronto Stores" : "No Stores"}
        </h2>
        <div className={styles.cardLayout}>
          {props.Coffedata.map((store) => (
            <Card
              key={store?.id}
              imageUrl={store?.imgUrl}
              route={`/coffee-store/${store?.id}`}
              name={store?.name}
              className={styles.card}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
